Add GitHub actions
NVIDIA/k8s-driver-manager pull request #3
Opened 2024-01-28 19:41 UTC by ArangoGutierrez

2024-01-28 20:29 UTC, elezar reviewed
My one question is whether the addition of the issue template makes sense at the moment. Let's rather leave it out until we have a better idea of what we want from users. In the case of GPU operator operands this would be different from standalone components. We may want to direct users to the `gpu-operator` repo instead.

2024-01-28 20:29 UTC, elezar commented on .github/ISSUE_TEMPLATE
> + - [ ] NVIDIA container library version from `nvidia-container-cli -V`
```suggestion
 - [ ] NVIDIA Container Toolkit version from `nvidia-ctk --version`
```

2024-01-28 20:29 UTC, elezar commented on .github/ISSUE_TEMPLATE
> + - [ ] Docker version from `docker version`
Docker is probably no longer relevant for k8s components.

2024-01-28 20:29 UTC, elezar commented on .github/workflows/images.yaml
> +      - name: Set up Docker Buildx
We need to set up Qemu here.

2024-01-28 20:30 UTC, elezar commented on versions.mk
> +BUILDIMAGE ?=  ghcr.io/nvidia/k8s-test-infra:$(BUILDIMAGE_TAG)
Missing newline.

2024-01-28 20:31 UTC, elezar commented on Makefile
> +		$(BUILDIMAGE)
Missing newline.

2024-01-28 20:31 UTC, elezar commented on Makefile
> +REGISTRY ?= nvidia
This is out of date. Should probably be ngc.

2024-01-28 20:34 UTC, ArangoGutierrez commented on Makefile
> +REGISTRY ?= nvidia
took inspiration from https://github.com/NVIDIA/k8s-device-plugin/blob/main/Makefile#L22

2024-01-28 20:35 UTC, ArangoGutierrez commented on .github/ISSUE_TEMPLATE
> + - [ ] NVIDIA container library version from `nvidia-container-cli -V`
Removed the issue template file for now

2024-01-30 11:19 UTC, elezar requested changes

2024-01-30 11:19 UTC, elezar commented on Makefile
> +	GOOS=$(GOOS) go build ./...
Can we create an issue to update this Makefile to match other projects. Specifically for how commands are built.

2024-01-30 11:19 UTC, elezar commented on go.mod
> +module github.com/NVIDIA/k8s-driver-manager
Nit: We're changing the module name not location.

2024-01-30 11:19 UTC, elezar commented on deployments/container/Dockerfile.ubi8
> +ARG GOLANG_VERSION=1.20.5
Let's use:
```suggestion
ARG GOLANG_VERSION=x.x.x
```
here so that we don't have to update it (and keep it in sync) when bumping the golang version.

2024-01-30 11:19 UTC, elezar commented on versions.mk
> +GOLANG_VERSION ?= 1.20.5
There were some glibc issues when upgrading from `1.20.4` to `1.20.5` which may require that the dockerfiles themselves also be updated. Could we rather skip the golang bump in this PR and assess the impact separately?

2024-01-30 11:19 UTC, elezar commented on .github/ISSUE_TEMPLATE
> + - [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)
A lot of these are not applicable to this component. Let's rather remove this template until we have a better grasp of what we need.

2024-01-30 11:19 UTC, elezar commented on .github/ISSUE_TEMPLATE
If this is removed in this commit ... let's rebase and remove the commit that adds this instead.

2024-01-30 12:00 UTC, ArangoGutierrez commented on go.mod
> +module github.com/NVIDIA/k8s-driver-manager
so keep go.mod pointing to gitlab?

2024-01-30 12:01 UTC, ArangoGutierrez commented on versions.mk
> +GOLANG_VERSION ?= 1.20.5
sure, yeah I remember those glibc issues

2024-01-30 12:01 UTC, ArangoGutierrez commented on .github/ISSUE_TEMPLATE
will do

2024-01-30 12:08 UTC, elezar commented on go.mod
> +module github.com/NVIDIA/k8s-driver-manager
No: Reword the commit message.

2024-01-30 12:21 UTC, ArangoGutierrez commented on go.mod
> +module github.com/NVIDIA/k8s-driver-manager
I see, thanks

2024-01-30 15:03 UTC, ArangoGutierrez commented on Makefile
> +	GOOS=$(GOOS) go build ./...
https://github.com/NVIDIA/k8s-driver-manager/issues/4

2024-01-30 15:14 UTC, elezar commented on versions.mk
> +GOLANG_VERSION ?= 1.20.4
Any reason to not use `1.20.2` and update the go version in a follow-up?

2024-01-30 15:17 UTC, ArangoGutierrez commented on versions.mk
> +GOLANG_VERSION ?= 1.20.4
not really, will fallback to .2

2024-01-30 15:18 UTC, ArangoGutierrez commented on versions.mk
> +GOLANG_VERSION ?= 1.20.4
oh we might need a test-infra .2

2024-01-30 15:21 UTC, ArangoGutierrez commented on versions.mk
> +GOLANG_VERSION ?= 1.20.4
https://github.com/NVIDIA/k8s-test-infra/pull/8

2024-01-30 15:43 UTC, ArangoGutierrez commented on versions.mk
> +GOLANG_VERSION ?= 1.20.4
done

2024-01-31 13:20 UTC, elezar approved these changes
Thanks @ArangoGutierrez

2024-01-31 15:27 UTC, merged